# Generated by Django 5.0.1 on 2024-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('user', 'thread')},
        ),
    ]
