# Generated by Django 5.0.1 on 2024-02-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_thread_title_alter_access_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('friend_a', 'friend_b')},
        ),
    ]
